// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvA8DfhhK_6LzkyWEkErqHlj8uY9EJeBY',
    appId: '1:569022180053:web:c42419443596daecba905c',
    messagingSenderId: '569022180053',
    projectId: 'staypal-7ee25',
    authDomain: 'staypal-7ee25.firebaseapp.com',
    storageBucket: 'staypal-7ee25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGWc--hHZ1OLeAtyw8prMTlzK3D3DYF9E',
    appId: '1:569022180053:android:1676464ccbe24b8aba905c',
    messagingSenderId: '569022180053',
    projectId: 'staypal-7ee25',
    storageBucket: 'staypal-7ee25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3s3s84tDNT6daOZQlpA4vh48_Hfbp-kE',
    appId: '1:569022180053:ios:9520ca6aa87ef4c4ba905c',
    messagingSenderId: '569022180053',
    projectId: 'staypal-7ee25',
    storageBucket: 'staypal-7ee25.firebasestorage.app',
    androidClientId: '569022180053-5h0n9debv66iek725piu8cefn899ugt7.apps.googleusercontent.com',
    iosClientId: '569022180053-2qkgu67j0l5hgiq89mb74l7cuo08213n.apps.googleusercontent.com',
    iosBundleId: 'com.example.staypal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3s3s84tDNT6daOZQlpA4vh48_Hfbp-kE',
    appId: '1:569022180053:ios:9520ca6aa87ef4c4ba905c',
    messagingSenderId: '569022180053',
    projectId: 'staypal-7ee25',
    storageBucket: 'staypal-7ee25.firebasestorage.app',
    androidClientId: '569022180053-5h0n9debv66iek725piu8cefn899ugt7.apps.googleusercontent.com',
    iosClientId: '569022180053-2qkgu67j0l5hgiq89mb74l7cuo08213n.apps.googleusercontent.com',
    iosBundleId: 'com.example.staypal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvA8DfhhK_6LzkyWEkErqHlj8uY9EJeBY',
    appId: '1:569022180053:web:6cbf72e6699d7aecba905c',
    messagingSenderId: '569022180053',
    projectId: 'staypal-7ee25',
    authDomain: 'staypal-7ee25.firebaseapp.com',
    storageBucket: 'staypal-7ee25.firebasestorage.app',
  );
}

