name: staypal
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7
  intl: ^0.17.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.3
  google_sign_in: ^6.2.1
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_database: ^11.3.5
  cached_network_image: ^3.3.1
  firebase_storage: ^12.4.5
  logger: ^2.0.2
  multi_select_flutter: ^4.1.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  provider: ^6.1.5
  share_plus: ^7.2.1
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.2.6
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.7
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/

flutter_native_splash:
  color: "#FF5722"
  image: "assets/icon/flutter_app_logo_base.png"
  android: true
  ios: true
  fullscreen: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/flutter_app_logo_base.png"
