import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:staypal/screens/homePage/views/home_page.dart';
import 'package:staypal/screens/profile/booking_complete.dart';
import 'package:staypal/screens/profile/views/my_profile.dart';
import 'package:staypal/screens/searchResult/views/search_result_page.dart';
//import 'package:staypal/screens/search_result/viewlisting.dart';
import 'package:staypal/DB/firebase_options.dart'; // Make sure this file exists and was generated by flutterfire
//import 'package:staypal/screens/auth/auth_entry_screen.dart';
//import 'package:staypal/screens/wishlistPage/wishlist_page.dart';
//import 'package:staypal/screens/homePage/home_page.dart';
import 'package:staypal/screens/profile/profile.dart';
//import 'package:staypal/screens/first_screen/firstscreen.dart';
//import 'package:staypal/screens/admin/dynamic_admin_panel.dart';
import 'package:staypal/screens/wishlistPage/views/wishlist_view.dart';
import 'package:staypal/screens/admin/views/admin_dashboard_view.dart';
//import 'package:staypal/screens/reviewSection/views/review.dart';
// import 'package:staypal/screens/auth/test_firestore_screen.dart'; // Uncomment if needed

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'StayPal',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),

      //home:  MyProfile(),
      home: HomePage(),
      //home:MainScreen(),
      //home:AuthEntryScreen(),
      //home: const AdminDashboard(),
      routes: {
        '/wishlist': (context) => WishListPage(),
        '/searchresult': (context) => SearchResultPage(),
        '/home': (context) => HomePage(),
        '/profile': (context) => MyProfile(),
      },

      // home: const TestFirestoreScreen(), // You can use this for testing
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('You have pushed the button this many times:'),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
